create table people (
id int generated by default as identity primary key,
name varchar(100) not null unique,
year_of_birth int not null check(year_of_birth > 1900)
);

create table books (
id int generated by default as identity primary key,
person_id int references people(id) on delete set null,
name varchar(100) not null unique,
author varchar(100) not null,
year_of_publication int not null check ( year_of_publication > 0 ),
took_at timestamp
);

INSERT INTO people (name, year_of_birth) VALUES ('Иванов Иван Иванович', 1970);
INSERT INTO people (name, year_of_birth) VALUES ('Алексеев Алексей Алексеевич', 1989);
INSERT INTO people (name, year_of_birth) VALUES ('Владимиров Владимир Владимирович', 1950);
INSERT INTO people (name, year_of_birth) VALUES ('Константинов Константин Константинович', 1995);
INSERT INTO people (name, year_of_birth) VALUES ('Петров Петр Петрович', 1960);
INSERT INTO people (name, year_of_birth) VALUES ('Сидоров Сидор Сидорович', 1940);
INSERT INTO people (name, year_of_birth) VALUES ('Васильев Василий Васильевич', 1980);
INSERT INTO people (name, year_of_birth) VALUES ('Иваньков Иван Иванович', 1970);

INSERT INTO books (name, author, year_of_publication) VALUES ('День опричника', 'Владимир Сорокин', 2006);
INSERT INTO books (name, author, year_of_publication) VALUES ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
INSERT INTO books (name, author, year_of_publication) VALUES ('Бытие и время', 'Мартин Хайдеггер', 1927);
INSERT INTO books (name, author, year_of_publication) VALUES ('Игра в бисер', 'Герман Гессе', 1943);
INSERT INTO books (name, author, year_of_publication) VALUES ('Психопатология обыденной жизни', 'Фрейд Зигмунд', 1904);
INSERT INTO books (name, author, year_of_publication) VALUES ('Над пропастью во ржи', 'Джэром Селинджер', 1951);
INSERT INTO books (name, author, year_of_publication) VALUES ('Git для профессионалов', 'Сельвия Чакон', 2021);
INSERT INTO books (name, author, year_of_publication) VALUES ('Принцип пирамиды Минто', 'Барбара Минто', 2005);